name: Basic CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -la

      - name: Run Hello Command
        run: echo "Hello from GitHub Actions"

      - name: Check Date
        run: date
